version: 2
jobs:
  build:
    working_directory: /usr/src/Artichoke
    docker:
      - image: dockbuild/centos7-devtoolset7-gcc7:latest
    steps:
      - checkout
      - run:
          name: Configure and Test
          command: |
            mkdir /usr/src/Artichoke-Tests && cd $_
            cmake ../Artichoke/Tests
            ctest

