name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.rst"
      - "Docs/**"
  pull_request:
    paths-ignore:
      - "**.rst"
      - "Docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        # 3.4.x: Excluded because of "error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory"
        cmake-version: [
          "2.8.x",
          "3.0.x", "3.8.x", "3.12.x", "3.14.x",
          "3.16.x", "3.17.x", "3.18.x", "3.19.x", "3.20.x", "3.21.x",
          "3.22.x", "3.23.x", "3.24.x", "3.25.x", "3.26.x", "3.28.x",
          "3.29.x", "3.30.x", "3.31.x", "4.0.x", "4.1.x",
          "latest"
          ]
        include:
          - cmake-version: "2.8.x"
            ctest-exclude: "IncludeDependencies-DifferentGenerator-Test"
          # Starting with CMake 4.x, compatibility with versions of CMake older than 3.5 is removed.
          - cmake-version: "4.0.x"
            cmake-args: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
          - cmake-version: "4.1.x"
            cmake-args: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
          - cmake-version: "latest"
            cmake-args: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"

    name: Tests on ${{ matrix.os }} using  ${{ matrix.cmake-version }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: ${{ matrix.cmake-version }}

    - name: Report CMake version
      run: |
        cmake --version

    - name: Setup ninja
      uses: urkle/action-get-ninja@e3ed0d4fc9ec9608cdc970133d71c980b6149631 # v1

    - name: Configure
      run: |
        mkdir ${{github.workspace}}/build && cd $_
        cmake -DCMAKE_BUILD_TYPE:STRING=Release ${{matrix.cmake-args }} ${{github.workspace}}/Tests

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest -C Release -V -E "${{ matrix.ctest-exclude }}"

  container-tests:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        image: [
          "dockbuild/almalinux8-devtoolset14-gcc14:latest"
          ]

    name: Tests on ${{ matrix.image }}
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Report CMake version
      run: |
        cmake --version

    - name: Configure
      run: |
        mkdir $GITHUB_WORKSPACE/build && cd $_
        cmake -DCMAKE_BUILD_TYPE:STRING=Release $GITHUB_WORKSPACE/Tests

    - name: Test
      run: |
        cd $GITHUB_WORKSPACE/build
        ctest -C Release -V

  pass: # This job does nothing and is only used for the branch protection
    if: always()
    needs:
    - tests
    - container-tests

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@2765efec08f0fd63e83ad900f5fd75646be69ff6 # v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
