name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.rst"
      - "Docs/**"
  pull_request:
    paths-ignore:
      - "**.rst"
      - "Docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        # 3.4.x: Excluded because of "error while loading shared libraries: libidn.so.11: cannot open shared object file: No such file or directory"
        cmake-version: [
          "2.8.x",
          "3.0.x", "3.8.x", "3.12.x", "3.14.x",
          "3.16.x", "3.17.x", "3.18.x", "3.19.x", "3.20.x", "3.21.x",
          "3.22.x", "3.23.x", "3.24.x", "3.25.x", "3.26.x", "3.28.x",
          "3.29.x", "3.30.x", "3.31.x", "4.0.x", "4.1.x",
          "latest"
          ]
        include:
          - cmake-version: "2.8.x"
            ctest-exclude: "IncludeDependencies-DifferentGenerator-Test"

    name: Tests on ${{ matrix.os }} using  ${{ matrix.cmake-version }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.14.1
      with:
        cmake-version: ${{ matrix.cmake-version }}

    - name: Setup ninja
      uses: urkle/action-get-ninja@v1

    - name: Configure
      run: |
        mkdir ${{github.workspace}}/build && cd $_
        cmake -DCMAKE_BUILD_TYPE:STRING=Release ${{github.workspace}}/Tests

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest -C Release -V -E ${{ matrix.ctest-exclude }}
